### ISSUE TITLE
Unable to upload files when on production

### ISSUE THREAD

**Issue by GaelTikeng** [edgestorejs/edgestore#59]
Hi, I have EdgeStore setup with edgestore provider in my NextJS app version 14. i've been facing this problem for close to a week already. Locally everything work fine, I'm able to upload files but on production i'm not. I have the following message on the preview when I open the networ tab`{message: "Missing edgestore-ctx cookie", code: "UNAUTHORIZED"}` 
And on the console i have this : 
`11-3392bd5869fc1126.js:1 Uncaught (in promise) 
EdgeStoreApiClientError: Missing edgestore-ctx cookie
    at ty (11-3392bd5869fc1126.js:1:58271)
    at async t_ (11-3392bd5869fc1126.js:1:58722)
    at async Object.upload (11-3392bd5869fc1126.js:1:62824)
    at async F (page-70a3e0cc9d17d698.js:1:11938)
﻿`

**Comment by perfectbase** [comment]
Hi @GaelTikeng 

Not sure what could be the problem.

A few things to check:
- is the `init` api running successfully on the network tab?
- are you using some kind of middleware that could be causing issues?

Maybe trying the troubleshooting steps in your production environment can help: 

https://edgestore.dev/docs/troubleshooting

You can also try to deploy one of the example apps and see it working on production, so you can try to find the difference between the example app and your app.

**Comment by GaelTikeng** [comment]
Down is the link of the app and the form where i'm using it. if you can please try and fill  the form and the see the error by yourself, maybe you will better guide me through solving this issue. Thanks
[https://www.jj-immigration.com/formulaire-devaluation](https://www.jj-immigration.com/formulaire-devaluation)

**Comment by perfectbase** [comment]
@GaelTikeng It seems that the init function is not running successfully in your app.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/19cbe680-05da-4118-980c-d5ddfd00243e">

Usually this can happen if you are using `createContext` and there is an error on it.
Maybe your server-side logs can give you an insight of what the problem is.
